### ISSUE TITLE
Running Dask on Cheyenne remotely

### ISSUE THREAD

**Issue by ksulia** [pangeo-data/pangeo#352]
@jhamman Thanks again for your help before! Bit of a followup question:

Is there a way to submit a (longer) python job without the hub/lab disconnecting from the server if wifi cuts out, similar to what would be done when submitting a WRF job, for example?

I was thinking there would be a way to request workers then run the code all within a python script via command and without using Jupyter Notebook, but this still would not get around the fact that a continuous connection to Cheyenne is required for the job to complete.  I figured there would probably also be issues submitting a job outside of the pangeo environment.

This may be a pretty complicated issue, so I understand if something like this has not yet been determined.  

Thanks!!

**Comment by mnlevy1981** [comment]
It sounds like the problem is that you are running `jupyter lab` from an interactive session, so when you lose wifi that session closes and jupyter shuts down. If that really is the issue, one way around it is to submit a job to they cheyenne queue to run `jupyter lab` or `start-jlab` rather than running it after running `qinteractive`. I have an extremely rough bash script to do just that in my path:

```
$ cat pangeo
#!/bin/bash

# This script submits a job to cheyenne queue to start jupyter remotely
# When the job is running, run
#
# $ qpeek {JOBID}
#
#
# To get port forwarding command that you need to run
#
### OPTIONS THAT USERS SHOULD SET

QUEUE=share
#QUEUE=economy
ACCOUNT=`cat ~/.cesm_proj`
NODES=1
CORES=1
HOURS=3
ROOT_PATH=/glade/work/mlevy/codes/pangeo-tutorial-august-2018
SET_PY_ENV="source activate pangeo"
LAUNCH_JLAB=./start-jlab

### ACTUAL SUBMIT (same for everyone)

QSUB_OPTS="-l inception=login -l walltime=${HOURS}:00:00 -l select=${NODES}:ncpus=${CORES}:mpiprocs=${CORES} -A ${ACCOUNT} -j oe -r n -m b -S /bin/bash -V -q ${QUEUE}"
SUBMIT="qsub ${QSUB_OPTS} -N pangeo"
RUNCMD="export LD_LIBRARY_PATH= ; ${SET_PY_ENV} ; cd ${ROOT_PATH} ; ${LAUNCH_JLAB}"
echo "Running: ${RUNCMD}"
echo "Submitting with: ${SUBMIT}"
echo "${RUNCMD}" | ${SUBMIT}
```

Note that you'll definitely need to edit `ROOT_PATH` to point your own directory, and you'll probably need to update `ACCOUNT` (the project code to charge on cheyenne) as well. This script was based on instructions from a [tutorial](https://github.com/NCAR/pangeo-tutorial-august-2018/blob/master/setup.md#launching-jupyter-and-dask-on-cheyenne) @kmpaul just gave; if those instructions don't match your current set-up you'll also need to change `SET_PY_ENV` (what do you need to do to your environment to load the proper python packages - currently assumes you have a conda environment named `pangeo`) and `LAUNCH_JLAB` (executable to run).

There are a few other (hopefully self-explanatory) variables you can modify, such as how many hours to request from the cheyenne queue and how many nodes / cores-per-node to request. To use it (note that I named the script `pangeo`):

```
$ pangeo
Running: export LD_LIBRARY_PATH= ; source activate pangeo ; cd /glade/work/mlevy/codes/pangeo-tutorial-august-2018 ; ./start-jlab
Submitting with: qsub -l inception=login -l walltime=3:00:00 -l select=1:ncpus=1:mpiprocs=1 -A P93300606 -j oe -r n -m b -S /bin/bash -V -q share -N pangeo
[JOBID].chadmin1
```

You'll get an email when the job begins (and it will also contain `JOBID` in it). To see the instructions for ssh-forwarding, you need to run

```
$ qpeek [JOBID]
[snip]
Run the following command on your desktop or laptop:

    ssh -N -l mlevy -L 8888:r8i0n25:8888 cheyenne.ucar.edu

Log in with your YubiKey/Cryptocard (there will be no prompt).
Then open a browser and go to http://localhost:8888.
[snip]
```

If you lose wi-fi, your job will still be running on cheyenne so when you have internet connectivity again you should be able to just re-run your `ssh -N -l ...` command.

**Comment by vprzybylo** [comment]
Hello, 

I work with Dr. Sulia and have further questions on the above instructions to reconnect to cheyenne if wifi disconnects or the server crashes.  Re-running the ssh -N -l .. command results in "channel 5: open failed: connect failed: Connection refused" and thus, I am unable to reload jupyter lab to retrieve the data output from the job -- it should output the data to a file but never gets there due to connection issues.

Overview:
I am not running qinteractive but submitting a job via qsub:  
qsub -I -l select=1:ncpus=4 -l walltime=05:00:00 -q economy -A ... 
then activating the pangeo environment, launching jupyter lab to start the workers, and 'ssh'ing in a local terminal.

I have tried to only launch the workers in jupyter lab and then run the main python script via command line after submitting a job but they are killed automatically due to using an excessive amount of the total available CPU resources (it can take hours to run even in parallel).  I am not sure how to run such a resource-intensive process on a batch node since I am new to running on Cheyenne and am not sure if this is the best option to avoid connectivity issues.

@mnlevy1981, is there any further assistance you can provide? 

It is greatly appreciated!

**Comment by mnlevy1981** [comment]
We are still working on the documentation, but a newer version of that script is available at

https://github.com/ncar/pangeo

That repository contains two directories:

* `client-side`: scripts to run from your laptop, including a single script that will launch jupyterlab and set up the ssh tunnel
* `server-side`: instructions for setting up a conda environment

The server-side directory is meant to be run once, and it sounds like you have something similar set up on cheyenne already so you can skip it. I think the `launch-pangeo-on-cheyenne` script in `client-side/` is what you want:

```
$ ./launch-pangeo-on-cheyenne
Token_Response:
Fri Aug 31 08:58:38 MDT 2018
waiting for job to run.............
Fri Aug 31 08:58:51 MDT 2018
----------
Job ID: 2232144
Job host: r8i7n4
Port to forward for jupyter lab: 8888
Token for jupyter lab: [token]
----------
Connection to cheyenne.ucar.edu closed.

****

Running create_tunnel...
ssh -N -L 8888:r8i7n4:8888 mlevy@cheyenne.ucar.edu
Tunnel PID: 80712
Use ^C to kill ssh tunnel
Waiting for tunnel to open
appending output to nohup.out
Token_Response:
Opening jupyter lab!
```

If you lose wi-fi, you can reconnect with

```
$ ./launch-pangeo-on-cheyenne -i 2232144
Getting remote host from Job ID...
Token_Response:
 r8i7n4/0
Reminder: your jupyter token is

****

Running create_tunnel...
ssh -N -L 8888:r8i7n4:8888 mlevy@cheyenne.ucar.edu
Tunnel PID: 81025
Use ^C to kill ssh tunnel
Waiting for tunnel to open
appending output to nohup.out
Token_Response:
Opening jupyter lab!
```

Note that `2232144` comes from the first output stream. You could also run

```
$ ./launch-pangeo-on-cheyenne -H r8i7n4
Reminder: your jupyter token is

****

Running create_tunnel...
ssh -N -L 8888:r8i7n4:8888 mlevy@cheyenne.ucar.edu
Tunnel PID: 81155
Use ^C to kill ssh tunnel
Waiting for tunnel to open
appending output to nohup.out
Token_Response:
Opening jupyter lab!
```

where the host `r8i7n4` is also found in the original output.

I intentionally redacted the token in the first output block, and it looks like there's a small bug in the script because the token self-redacted when I tried to reconnect.

**Comment by vprzybylo** [comment]
Thanks for the help and the new script! However, I cannot get it working.  It seems to be erroring on the ssh call in launch_job pasted below saying "ssh: Could not resolve hostname cheyenne.ucar.edu: Name or service not known"

(ssh -t ${REM_USER}@cheyenne.ucar.edu "$(declare -f launch_job); launch_job ${REM_USER} ${WALLTIME} ${CONDA_ENV} ${ACCOUNT}" ; echo $? > .ret_code) | tee .last_run.log

I have tried running launch-pangeo-on-cheyenne with the options of my environment name and user name.

Thanks!

**Comment by mnlevy1981** [comment]
Huh, that looks like you can't connect to `cheyenne` at all... can you `ping` the machine?

```
$ ping cheyenne.ucar.edu
PING cheyenne.ucar.edu (128.117.181.196): 56 data bytes
64 bytes from 128.117.181.196: icmp_seq=0 ttl=62 time=4.001 ms
64 bytes from 128.117.181.196: icmp_seq=1 ttl=62 time=4.145 ms
^C
```

If so, what happens if you try to `ssh` directly?

```
$ ssh [user]@cheyenne.ucar.edu
```

If you can't use the new script but can connect directly then I'm not sure what to suggest. If you can't ping it, try requesting specific log-in nodes:

```
$ ping cheyenne1.ucar.edu
PING cheyenne1.ucar.edu (128.117.181.195): 56 data bytes
64 bytes from 128.117.181.195: icmp_seq=0 ttl=62 time=3.991 ms
64 bytes from 128.117.181.195: icmp_seq=1 ttl=62 time=4.002 ms
^C
```

basically, `cheyenne[#].ucar.edu` for `[#]` between 1 and 6. If you can connect to one of those, just change `cheyenne.ucar.edu` to `cheyenne[#].ucar.edu` everywhere in the script. Let me know if you need to do this, because if so I can (eventually) add a hostname option to the script to let you make this change from the command line.

**Comment by vprzybylo** [comment]
I don't have permission to ping.  But I can ssh into cheyenne just fine using:
ssh -Y -l przybylo cheyenne.ucar.edu or ssh -Y przybylo@cheyenne.ucar.edu

Usually when I open jupyter lab I use:
ssh -N -L 8888:r14i6n12:8888 -L 8787:r14i6n12:8787 przybylo@cheyenne.ucar.edu

**Comment by mnlevy1981** [comment]
@davidedelvento -- can you help with this at all? @vprzybylo can ssh into cheyenne from a command line, but not from within a bash script... do you have access to logs that might indicate what's going on?

For what it's worth, I've used this script from outside the NCAR network before... there's no dependency on having an internal NCAR IP address or anything.

**Comment by davidedelvento** [comment]
I do not have access to attempted login logs. However if your error is `Could not resolve hostname cheyenne.ucar.edu` that has nothing to do with Cheyenne and will not show up in our logs.

The problem seems to be your bash script not being able to access DNS on the machine you are using. To debug the issue, try using another machine and see if the problem persists. Try simplifying your bash script to the level of simply doing `ssh -Y -l przybylo cheyenne.ucar.edu`. Note that your script is using the `przybylo@cheyenne.ucar.edu` instead of the `-l przybylo cheyenne.ucar.edu` which should be equally functional, but perhaps your local ssh implementation has quirks?

**Comment by vprzybylo** [comment]
Progress has been made on getting the script to run!  I have it to the point where it runs to the end mimicking the output you shared above but when it opens jupyter lab locally I receive the, "This site can’t be reached." It falls into the if statement where...

if [ `uname` == "Darwin" ]; then
      open http://localhost:${LOCALPORT}
....
but is unable to open the lab.  The only difference in the output from the script is that my tunnel PID is 4 #'s instead of 5?? Any help and/or ideas are appreciated. And thanks for the quick responses.

**Comment by mnlevy1981** [comment]
I'd like to see what your tunnel looks like - can you copy and paste the output from your script that is similar to

```
Running create_tunnel...
ssh -N -L 8888:r8i7n4:8888 mlevy@cheyenne.ucar.edu
```

And what do you mean when you say "unable to open the lab"? Does your browser open with an error message? If so, (a) what message are you getting, and (b) what number is showing up to the right of the colon in `http://localhost:####`?

**Comment by vprzybylo** [comment]
Running create_tunnel...
ssh -N -L 8888:r6i6n22:8888 przybylo@cheyenne.ucar.edu
Tunnel PID: 9474
Use ^C to kill ssh tunnel

Yes, my browser opens with "This site can’t be reached" to port 8888 to the right of the colon.  I have all other notebooks shut down so this port is definitely available.

**Comment by willirath** [comment]
I've seen stuff like this fail when `localhost` was not properly resolved to `127.0.0.1`. The fix was to specify the hostname in the SSH call.  Changing <https://github.com/NCAR/pangeo/blob/master/client-side/launch-pangeo-on-cheyenne#L214> to

```shell
cmd="ssh -N -L localhost:${LOCALPORT}:${REM_HOST}:${PORT} ${REM_USER}@cheyenne.ucar.edu"
```

could do the trick.

**Comment by vprzybylo** [comment]
No luck with the new cmd line.  Here is another instance that now has a longer tunnel PID, not sure that matters.

Running create_tunnel...
ssh -N -L 8888:r9i0n13:8888 przybylo@cheyenne.ucar.edu
Tunnel PID: 10166
Use ^C to kill ssh tunnel

**Comment by willirath** [comment]
> `ssh -N -L 8888:r9i0n13:8888 przybylo@cheyenne.ucar.edu`

This does not look like the `cmd` was changed.

**Comment by mnlevy1981** [comment]
@willirath I updated the script in the NCAR/pangeo repository, thanks for the tip!

@vprzybylo if you run `$ git pull` you can update your copy of the script (even though it sounds like maybe it doesn't matter in your case?)

Before you do that, though -- if you run

```
$ lsof -p 10166
```

Do you get any output? If so, can you paste it here?

**Comment by vprzybylo** [comment]
It must not have saved or I copied the older run, sorry.  Here is the new output, which looks fine, but still no luck when the chrome browser opens.

ssh -N -L localhost:8888:r9i0n13:8888 przybylo@cheyenne.ucar.edu

I would say it could be something with my firewall but it opens fine when I use the instructions from http://pangeo.io/setup_guides/hpc.html

**Comment by vprzybylo** [comment]
And i have no output from lsof -p 10166

**Comment by mnlevy1981** [comment]
If you copy and paste the tunnel command

```
ssh -N -L localhost:8888:r9i0n13:8888 przybylo@cheyenne.ucar.edu
```

(replacing `r9i0n13` with the latest remote host name you connected to) into a new terminal window and set up the tunnel that way, can you connect to http://localhost:8888 ?

**Comment by vprzybylo** [comment]
If I ssh in a new terminal while the script is still running after, "Opening jupyter lab!", I receive 

bind: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 8888
Could not request local forwarding.

If I kill the script and run the ssh command from a new terminal after I still receive the, "This site can’t be reached" when opening http://localhost:8888

**Comment by vprzybylo** [comment]
The host name is wrong, port is fine!  It is now up and running and I can try my longer scripts that usually require reconnecting.  I didn't know about qpeek or think to check the name.  Thanks so much.  I will also look into the script to accurately capture the name.

**Comment by mnlevy1981** [comment]
Glad it's working! When you get a chance, if you can recreate the issue, can you open a ticket at

https://github.com/ncar/pangeo/issues

I have some theories on how to improve the script (unique log files each time you run?), but I think the NCAR repository will be a better place for discussing them.
